In [2]:
import numpy as np
# If we want to generate walsh code 2 so  power of 2 is 1 
# write order of 2 for e.g 2^3 = 8 for walsh 8\
# walsh code 8 => order 3
# walsh code 16 => order 4
def walsh_code(order):
    #basic element(seed) of walsh code generator
    W = np.array([0])
    for i in range(order):
        W = np.tile(W, (2, 2))
        half = 1 << i
        W[half:, half:] = np.logical_not(W[half:, half:])
    return W

print("Walsh code 2 (W2) is:",walsh_code(2))


Walsh code 2 (W2) is: [[0 0 0 0]
 [0 1 0 1]
 [0 0 1 1]
 [0 1 1 0]]


In [3]:
print("Walsh code is (W4):",walsh_code(4))

Walsh code is (W16): [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0]
 [0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0]
 [0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]
 [0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0]
 [0 1 1 0 0 1 1 0 1 0 0 1 1 0 0 1]
 [0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1]
 [0 0 1 1 1 1 0 0 1 1 0 0 0 0 1 1]
 [0 1 1 0 1 0 0 1 1 0 0 1 0 1 1 0]]
